/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockUSDC } from "./MockUSDC";
export type { MockUSDT } from "./MockUSDT";
export type { MockWBTC } from "./MockWBTC";
export type { MockWETH } from "./MockWETH";
